# Frontend PersistentVolume
apiVersion: v1
kind: PersistentVolume
metadata:
  name: frontend-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: frontend-nfs
  nfs:
    server: 172.31.11.149
    path: /data

---
# Frontend PersistentVolumeClaim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frontend-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: frontend-nfs
  resources:
    requests:
      storage: 5Gi

---
# Frontend Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
          volumeMounts:
            - name: frontend-storage
              mountPath: /usr/share/nginx/html
      volumes:
        - name: frontend-storage
          persistentVolumeClaim:
            claimName: frontend-pvc

---
# Frontend NodePort Service
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
